In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_csv('multiple_linear_regression_dataset.csv')

In [4]:
df.describe()

area    bedrooms         age          price
count   800.00000  800.000000  800.000000     800.000000
mean   2342.89375    2.947500   14.382500  135028.830000
std     972.78049    1.436079    8.650563   53923.976963
min     601.00000    1.000000    0.000000    -314.000000
25%    1553.75000    2.000000    7.000000   93519.250000
50%    2286.50000    3.000000   14.000000  134974.000000
75%    3213.75000    4.000000   22.000000  173372.250000
max    3998.00000    5.000000   29.000000  273153.000000

In [5]:
df['bedrooms'].nunique()

5

In [6]:
df['bedrooms'].unique()

array([1, 5, 3, 4, 2], dtype=int64)

In [7]:
df['bedrooms'].value_counts()

1    172
5    166
3    164
2    164
4    134
Name: bedrooms, dtype: int64

In [8]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      800 non-null    int64
 1   bedrooms  800 non-null    int64
 2   age       800 non-null    int64
 3   price     800 non-null    int64
dtypes: int64(4)
memory usage: 25.1 KB


In [10]:
X = df.drop(columns=['price'])
y = df['price']

In [11]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=45)

In [12]:
x_train

area  bedrooms  age
266  2791         2    1
464  1766         1   22
575  3449         1   26
447  2441         2   25
605  1666         3   22
..    ...       ...  ...
725  2676         2    4
607  3044         5   28
544  2279         3    5
643  2171         3    8
414  1580         5   16

[640 rows x 3 columns]

In [13]:
reg = LinearRegression()

In [14]:
reg.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred = reg.predict(x_test)
y_pred

array([183488.16711442, 211174.49315161, 137242.63347307, 126181.42108534,
        76204.93962948, 105000.09348796, 122852.16648877,  78522.04427471,
        98520.26692824, 170746.01321964, 147265.6951779 , 139557.12960175,
        96035.91865829, 113415.5399947 , 191856.87669734, 196668.30360993,
        73005.79009636, 180489.31276465, 219898.68670116, 113840.3242487 ,
        98734.24747679,  73799.21600968, 127815.64599558, 122777.06051473,
       106593.66116081, 127156.9873271 , 109739.29694281,  60475.54275827,
       134692.46293781, 185733.10928298, 187381.65571822, 185673.46833921,
       111601.57025386, 201960.36304442, 134002.82670256,  99177.76176442,
       130114.06126122, 174053.34061245,  81586.426563  , 204982.62993623,
       236063.9515272 ,  96018.6333089 ,  85675.74086044, 105933.28380832,
       113018.27561243, 149987.71053821,  46343.54688983, 104492.02240243,
       127099.95489987,  37134.96879656, 109634.93208602, 126967.26164691,
       174963.3992427 ,  

In [16]:
pd.DataFrame({'y_test':y_test,'y_predict':y_pred})

y_test      y_predict
418  141287  183488.167114
67   203576  211174.493152
204  135924  137242.633473
250  141173  126181.421085
472   65020   76204.939629
..      ...            ...
551  242963  213627.884182
285  139037  123402.393625
48   131790  114834.004691
519  181154  188061.077758
413  140981  146509.387499

[160 rows x 2 columns]

In [17]:
reg.coef_

array([  49.40642143, 9304.48809281, -809.50677636])

In [18]:
reg.intercept_

2830.851784695318

In [19]:
print("MSE:",mean_squared_error(y_test,y_pred))
print("R2 Score: ",r2_score(y_test,y_pred))
print("RMSE:",np.sqrt(mean_squared_error(y_test,y_pred)))

MSE: 347295740.97041124
R2 Score:  0.8627828018134687
RMSE: 18635.87242310945
